-- MySQL Script generated by MySQL Workbench
-- Mon Sep 19 07:07:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cpf Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cpf Cliente` (
  `cod_cpf_cli` INT NOT NULL,
  `numeroCpf_cli` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_cpf_cli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CNPJ Clienete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CNPJ Clienete` (
  `cod-CNPJ_cli` INT NOT NULL,
  `Numero-CNPJ_cli` VARCHAR(45) NULL,
  PRIMARY KEY (`cod-CNPJ_cli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cpf Cliente_has_CNPJ Clienete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cpf Cliente_has_CNPJ Clienete` (
  `cpf Cliente_cod_cpf_cli` INT NOT NULL,
  `CNPJ Clienete_cod-CNPJ_cli` INT NOT NULL,
  PRIMARY KEY (`cpf Cliente_cod_cpf_cli`, `CNPJ Clienete_cod-CNPJ_cli`),
  INDEX `fk_cpf Cliente_has_CNPJ Clienete_CNPJ Clienete1_idx` (`CNPJ Clienete_cod-CNPJ_cli` ASC) VISIBLE,
  INDEX `fk_cpf Cliente_has_CNPJ Clienete_cpf Cliente1_idx` (`cpf Cliente_cod_cpf_cli` ASC) VISIBLE,
  CONSTRAINT `fk_cpf Cliente_has_CNPJ Clienete_cpf Cliente1`
    FOREIGN KEY (`cpf Cliente_cod_cpf_cli`)
    REFERENCES `mydb`.`cpf Cliente` (`cod_cpf_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cpf Cliente_has_CNPJ Clienete_CNPJ Clienete1`
    FOREIGN KEY (`CNPJ Clienete_cod-CNPJ_cli`)
    REFERENCES `mydb`.`CNPJ Clienete` (`cod-CNPJ_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cartao debito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartao debito` (
  `idcartao debito` INT NOT NULL,
  `numero do cartao` INT NULL,
  `validade` VARCHAR(45) NULL,
  `banco` VARCHAR(45) NULL,
  PRIMARY KEY (`idcartao debito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cartao credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartao credito` (
  `idcartao credito` INT NOT NULL,
  `numero do cartao` INT NULL,
  `validade` VARCHAR(45) NULL,
  `banco` VARCHAR(45) NULL,
  `dividir vezes` VARCHAR(45) NULL,
  PRIMARY KEY (`idcartao credito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cartao debito_has_cartao credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cartao debito_has_cartao credito` (
  `cartao debito_idcartao debito` INT NOT NULL,
  `cartao credito_idcartao credito` INT NOT NULL,
  PRIMARY KEY (`cartao debito_idcartao debito`, `cartao credito_idcartao credito`),
  INDEX `fk_cartao debito_has_cartao credito_cartao credito1_idx` (`cartao credito_idcartao credito` ASC) VISIBLE,
  INDEX `fk_cartao debito_has_cartao credito_cartao debito1_idx` (`cartao debito_idcartao debito` ASC) VISIBLE,
  CONSTRAINT `fk_cartao debito_has_cartao credito_cartao debito1`
    FOREIGN KEY (`cartao debito_idcartao debito`)
    REFERENCES `mydb`.`cartao debito` (`idcartao debito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartao debito_has_cartao credito_cartao credito1`
    FOREIGN KEY (`cartao credito_idcartao credito`)
    REFERENCES `mydb`.`cartao credito` (`idcartao credito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`forma de pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`forma de pagamento` (
  `idforma de pagamento` INT NOT NULL,
  `Pix` TINYINT NULL,
  `cartao/debito/credito` TINYINT NULL,
  `Boleto` TINYINT NULL,
  PRIMARY KEY (`idforma de pagamento`),
  INDEX `fk_forma de pagamento_cartao debito_has_cartao credito1_idx` (`cartao/debito/credito` ASC) VISIBLE,
  CONSTRAINT `fk_forma de pagamento_cartao debito_has_cartao credito1`
    FOREIGN KEY (`cartao/debito/credito`)
    REFERENCES `mydb`.`cartao debito_has_cartao credito` (`cartao debito_idcartao debito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forma de pagamento_cartao debito_has_cartao credito2`
    FOREIGN KEY (`cartao/debito/credito`)
    REFERENCES `mydb`.`cartao debito_has_cartao credito` (`cartao credito_idcartao credito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `cod_cli` INT NOT NULL,
  `endereco_cli` VARCHAR(45) NULL,
  `contato_cli` VARCHAR(45) NULL,
  `identificação` VARCHAR(45) NULL,
  `cpf Cliente_has_CNPJ Clienete_cpf Cliente_cod_cpf_cli` INT NOT NULL,
  `cpf Cliente_has_CNPJ Clienete_CNPJ Clienete_cod-CNPJ_cli` INT NOT NULL,
  `forma de pagamento_idforma de pagamento` INT NOT NULL,
  PRIMARY KEY (`cod_cli`, `forma de pagamento_idforma de pagamento`),
  INDEX `fk_Cliente_cpf Cliente_has_CNPJ Clienete1_idx` (`cpf Cliente_has_CNPJ Clienete_cpf Cliente_cod_cpf_cli` ASC, `cpf Cliente_has_CNPJ Clienete_CNPJ Clienete_cod-CNPJ_cli` ASC) VISIBLE,
  INDEX `fk_Cliente_forma de pagamento1_idx` (`forma de pagamento_idforma de pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_cpf Cliente_has_CNPJ Clienete1`
    FOREIGN KEY (`cpf Cliente_has_CNPJ Clienete_cpf Cliente_cod_cpf_cli` , `cpf Cliente_has_CNPJ Clienete_CNPJ Clienete_cod-CNPJ_cli`)
    REFERENCES `mydb`.`cpf Cliente_has_CNPJ Clienete` (`cpf Cliente_cod_cpf_cli` , `CNPJ Clienete_cod-CNPJ_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_forma de pagamento1`
    FOREIGN KEY (`forma de pagamento_idforma de pagamento`)
    REFERENCES `mydb`.`forma de pagamento` (`idforma de pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `razão social_for` VARCHAR(45) NULL,
  `enderco_for` VARCHAR(45) NULL,
  `cnpj_for` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `cnpj_for_UNIQUE` (`cnpj_for` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL,
  `nome_prod` VARCHAR(45) NULL,
  `categoria_prod` VARCHAR(45) NULL,
  `valor_prod` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disponibilizando um produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disponibilizando um produto` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Produto_idProduto`),
  INDEX `fk_Fornecedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Produto_Fornecedor_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrga` (
  `idEntrga` INT NOT NULL,
  `valor do frete` INT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`idEntrga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `local` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstoque`),
  INDEX `fk_Estoque_Entrga1_idx` (`local` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Entrga1`
    FOREIGN KEY (`local`)
    REFERENCES `mydb`.`Entrga` (`valor do frete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disponibilidae Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disponibilidae Produto` (
  `Estoque_idEstoque` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`Estoque_idEstoque`, `Produto_idProduto`),
  INDEX `fk_Estoque_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Estoque_has_Produto_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_has_Produto_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rastreamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rastreamento` (
  `Cliente_cod_cli` INT NOT NULL,
  `Entrga_idEntrga` INT NOT NULL,
  `Cod restreio` VARCHAR(45) NULL,
  PRIMARY KEY (`Cliente_cod_cli`, `Entrga_idEntrga`),
  INDEX `fk_Cliente_has_Entrga_Entrga1_idx` (`Entrga_idEntrga` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Entrga_Cliente1_idx` (`Cliente_cod_cli` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Entrga_Cliente1`
    FOREIGN KEY (`Cliente_cod_cli`)
    REFERENCES `mydb`.`Cliente` (`cod_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Entrga_Entrga1`
    FOREIGN KEY (`Entrga_idEntrga`)
    REFERENCES `mydb`.`Entrga` (`idEntrga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `Status do pedido` VARCHAR(45) NULL,
  `Descrição` VARCHAR(45) NULL,
  `Cliente_cod_cli` INT NOT NULL,
  `frete` FLOAT NULL,
  `forma de pagamento_idforma de pagamento` INT NOT NULL,
  `Rastreamento_Cliente_cod_cli` INT NOT NULL,
  `Rastreamento_Entrga_idEntrga` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_cod_cli`, `forma de pagamento_idforma de pagamento`, `Rastreamento_Cliente_cod_cli`, `Rastreamento_Entrga_idEntrga`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_cod_cli` ASC) VISIBLE,
  INDEX `fk_Pedido_forma de pagamento1_idx` (`forma de pagamento_idforma de pagamento` ASC) VISIBLE,
  INDEX `fk_Pedido_Rastreamento1_idx` (`Rastreamento_Cliente_cod_cli` ASC, `Rastreamento_Entrga_idEntrga` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_cod_cli`)
    REFERENCES `mydb`.`Cliente` (`cod_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_forma de pagamento1`
    FOREIGN KEY (`forma de pagamento_idforma de pagamento`)
    REFERENCES `mydb`.`forma de pagamento` (`idforma de pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Rastreamento1`
    FOREIGN KEY (`Rastreamento_Cliente_cod_cli` , `Rastreamento_Entrga_idEntrga`)
    REFERENCES `mydb`.`Rastreamento` (`Cliente_cod_cli` , `Entrga_idEntrga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto por pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto por pedido` (
  `Produto_idProduto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_cod_cli` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Pedido_idPedido`, `Pedido_Cliente_cod_cli`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_cod_cli` ASC) VISIBLE,
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_cod_cli`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_cod_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dropship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dropship` (
  `iddropship` INT NOT NULL,
  `Razão social` VARCHAR(45) NULL,
  `Local` VARCHAR(45) NULL,
  PRIMARY KEY (`iddropship`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos/drop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos/drop` (
  `dropship_iddropship` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`dropship_iddropship`, `Produto_idProduto`),
  INDEX `fk_dropship_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_dropship_has_Produto_dropship1_idx` (`dropship_iddropship` ASC) VISIBLE,
  CONSTRAINT `fk_dropship_has_Produto_dropship1`
    FOREIGN KEY (`dropship_iddropship`)
    REFERENCES `mydb`.`dropship` (`iddropship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dropship_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
